apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-back
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tereza-arta/k8s-manifests.git
    targetRevision: main
    path: environments/staging/front
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
